name: quote_details
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  component_library:
    path: ../../component_library
  domain_models:
    path: ../../domain_models
  fav_qs_api:
    path: ../../fav_qs_api
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  quote_repository:
    path: ../../quote_repository
  share_plus: ^7.0.0 # Upgraded to the latest version
  user_repository:
    path: ../../user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_test: ^1.1.0
  test: ^1.16.8
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true